from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from backend.schemas.paper import PaperChunk, PaperMetadata

class AnalysisMode(str, Enum):
  """Supported analysis modes"""

  SINGLE_PAPER_ANALYSIS = "single_paper_analysis"
  PAPER_COMPARISON = "paper_comparison"
  ASK_THE_PAPER = "ask_the_paper"

class AgentRole(str, Enum):
  """Agent roles used in the system"""

  PLANNER = "planner"
  READER = "reader"
  RAG = "rag"
  CRITIC = "critic"
  WRITER = "writer"

class AgentTask(BaseModel):
  """
    A single task generated by the Planner Agent.

    Example:
    - extract_contributions
    - analyze_method
    - summarize_experiments
  """

  task_id: str = Field(..., min_length=1)
  name: str = Field(..., min_length=1)
  description: str = Field(default="")
  assigned_to: AgentRole | None = Field(default=None)
  priority: int = Field(default=1, ge=1, le=5)

  model_config = ConfigDict(use_enum_values=True)

  @field_validator("task_id", "name", "description")
  @classmethod
  def strip_text(cls, value: str) -> str:
    return value.strip()
  

class AnalysisPlan(BaseModel):
  """
    output of planner agent.

    It tells the system what to analyze and which focus questions should guide later agents.
  """

  model_config = ConfigDict(use_enum_values=True)

  mode: AnalysisMode = Field(default=AnalysisMode.SINGLE_PAPER_ANALYSIS)
  tasks: list[AgentTask] = Field(default_factory=list)
  focus_questions: list[str] = Field(default_factory=list)
  required_sections: list[str] = Field(default_factory=list)
  need_retrieval: bool = Field(default=True)
  notes: str|None = Field(default=None)

  @field_validator("focus_questions", "required_sections")
  @classmethod
  def clean_string_list(cls, values: list[str]) -> list[str]:
    cleaned = []
    for item in values:
      item = item.strip()
      if item:
        cleaned.append(item)
    return cleaned
  
  @field_validator("notes")
  @classmethod
  def strip_optional_text(cls, value: str|None) -> str|None :
    if value is None:
      return None
    value = value.strip()
    return value or None
  

#RAG的桥梁，连接PaperChunk -> Retriever -> Reader/Critic/Writer
class EvidenceItem(BaseModel):
  """
    A single piece of evidence retrieved from chunks.

    This object is designed to be cited by Reader / Critic / Writer outputs.
  """

  evidence_id: str = Field(..., min_length=1)
  query: str|None = Field(default=None)

  chunk_id: str = Field(..., min_length=1)
  paper_id: str|None = Field(default=None)

  text: str = Field(..., min_length=1)
  score: float|None = Field(default=None)

  page_start: int|None = Field(default=None, ge=1)
  page_end: int|None = Field(default=None, ge=1)
  section: str|None = Field(default=None)

  @field_validator("query", "paper_id", "section")
  @classmethod
  def strip_optional_text(cls, value: str|None) -> str|None:
    if value is None:
      return None
    value = value.strip()
    return value or None
  
  @model_validator(mode="after")
  def validate_page_range(self) -> "EvidenceItem":
    if self.page_start is not None and self.page_end is not None:
      if self.page_end < self.page_start:
        raise ValueError("Page end must be grater than or euqal to page start")
    return self
  
  @classmethod
  def from_chunk(cls, chunk: PaperChunk, evidence_id: str, query: str|None = None, score: float|None = None) -> "EvidenceItem":
    """
      Create an EvidenceItem from a paperchunk.
      This helper is useful in retriever.py
    """

    return cls(
      evidence_id = evidence_id,
      query = query,
      chunk_id = chunk.chunk_id,
      paper_id = chunk.paper_id,
      text = chunk.text,
      score = score,
      page_start = chunk.page_start,
      page_end = chunk.page_end,
      section = chunk.section,
    )
  

class EvidenceBundle(BaseModel):
  """
    A group of retrieved evidence items.
    Usually generated by retriever.py or RAG Agent.
  """

  query_list: list[str] = Field(default_factory=list)
  items: list[EvidenceItem] = Field(default_factory=list)

  @field_validator("query_list")
  @classmethod
  def clean_query_list(cls, values: list[str]) -> list[str]:
    cleaned = []
    for item in values:
      item = item.strip()
      if item:
        cleaned.append(item)
    return cleaned
  
  def top_k(self, k: int) -> list[EvidenceItem]:
    """Return top-k evidence items"""
    return self.items[:k]
  
  def evidence_ids(self) -> list[str]:
    """return all evidence IDs"""
    return [item.evidence_id for item in self.items]
  


class PlannerInput(BaseModel):
  """input of planner agent"""

  paper_metadata: PaperMetadata
  user_query: str = Field(
    default="分析这篇论文然后生成结构化的阅读报告."
  )

  @field_validator("user_query")
  @classmethod
  def strip_user_query(cls, value: str) -> str:
    value = value.strip()
    if not value:
      raise ValueError("user_query cannot bu empty")
    return value
  


class ReaderInput(BaseModel):
  """Input of Reader Agent"""

  paper_metadata: PaperMetadata
  chunks: list[PaperChunk] = Field(default_factory=list)
  analysis_plan: AnalysisPlan
  evidence_bundle:EvidenceBundle|None = None

  @model_validator(mode="after")
  def validate_context(self) -> "ReaderInput":
    has_chunks = bool(self.chunks)
    has_evidence = self.evidence_bundle is not None and bool(self.evidence_bundle.items)
    if not has_chunks and not has_evidence:
      raise ValueError("ReaderInput requires either chunks or evidence_bundle.")
    return self
  # def validate_chunks(self) -> "ReaderInput":
  #   if not self.chunks:
  #     raise ValueError("ReaderInput requires at least one paper chunk")
  #   return self
  


#负责客观总结：论文做了什么？ 方法是什么？ 实验是什么？ 结论是什么
class ReaderNotes(BaseModel):
  """
    Output of Reader Agent.

    Reader agent should focus on faithful extraction and summarization.
    It should not perform deep criticism here.
  """

  problem_statement: str = Field(default="")
  background: str = Field(default="")
  main_contributions: list[str] = Field(default_factory=list)
  method_summary: str = Field(default="")
  experiment_summary: str = Field(default="")
  conclusion_summary: str = Field(default="")
  key_terms: list[str] = Field(default_factory=list)
  important_evidence_ids: list[str] = Field(default_factory=list)

  @field_validator(
    "problem_statement",
    "background",
    "method_summary",
    "experiment_summary",
    "conclusion_summary"
  )
  @classmethod
  def strip_text(cls, value: str)-> str:
    return value.strip()
  
  @field_validator("main_contributions", "key_terms", "important_evidence_ids")
  @classmethod
  def clean_string_list(cls, values: list[str]) -> list[str]:
    cleaned = []
    for item in values:
      item = item.strip()
      if item:
        cleaned.append(item)
    return cleaned
  

class CriticInput(BaseModel):
  """Input of Critic Agent"""

  paper_metadata: PaperMetadata
  reader_notes: ReaderNotes
  evidence_bundle: EvidenceBundle|None = None


#负责批判性分析：实验是否充分？ 创新新是否足够？ 缺少哪些baseline？ 复现难度？
class CriticNotes(BaseModel):
  """
    output of Critic Agent.
    this is the key module that differentiates this project from simple paper summarizer.
  """
  strengths: list[str] = Field(default_factory=list)
  limitations: list[str] = Field(default_factory=list)
  missing_experiments: list[str] = Field(default_factory=list)
  potential_weaknesses: list[str] = Field(default_factory=list)
  novelty_assessment: str = Field(default="", description="新颖性评估")
  reliability_assessment: str = Field(default="")
  reproducibility_notes: list[str] = Field(default_factory=list)
  evidence_ids: list[str] = Field(default_factory=list)

  @field_validator(
    "strengths",
    "limitations",
    "missing_experiments",
    "potential_weaknesses",
    "reproducibility_notes",
    "evidence_ids"
  )
  @classmethod
  def clean_string_list(cls, values: list[str])->list[str]:
    cleaned = []
    for item in values:
      item = item.strip()
      if item:
        cleaned.append(item)
    return cleaned
  
  @field_validator("novelty_assessment", "reliability_assessment")
  @classmethod
  def strip_text(cls, value: str)-> str:
    return value.strip()
  

#负责整合：基于前置agent结构化结果输出报告，而不是重新读论文
class WriterInput(BaseModel):
  """
    Input of writer agent.
    writer agent uses structured outputs from previous agents to generate the final report.
  """ 

  paper_metadata: PaperMetadata
  analysis_plan: AnalysisPlan
  reader_notes: ReaderNotes
  critic_notes: CriticNotes
  evidence_bundle: EvidenceBundle|None = None
  output_language: Literal["zh", "en"] = "zh"
  analysis_depth: Literal["quick", "standard", "deep"] = "standard"
  target_audience: Literal["general", "researcher", "reviewer"] = "researcher"
  report_template: Literal["standard", "review", "reproducibility"] = "standard"
  custom_sections: list[str] = Field(default_factory=list, max_length=20)
