from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, field_validator

class ReportFormat(str, Enum):
  """Supported report output formats"""

  MARKDOWN = "markdown"
  PDF = "pdf"
  HTML = "html"


class ReportSection(BaseModel):
  """
    A structured section in the final report

    Each section can be converted into a MarkDown block.
  """

  title:str = Field(..., min_length=1)
  content:str = Field(default="")
  order:int = Field(default=0, ge=0)
  evidence_ids:list[str] = Field(default_factory=list)

  @field_validator("title", "content")
  @classmethod
  def strip_text(cls, value:str) -> str:
    return value.strip()
  
  @field_validator("evidence_ids")
  @classmethod
  def clean_evidence_ids(cls, values:list[str]) -> list[str]:
    cleaned = []
    for item in values:
      item = item.strip()
      if item:
        cleaned.append(item)
    return cleaned
  
  def to_markdown(self, heading_level:int = 2) -> str:
    """
      Convert the section to markdown.

      Example:
        ## Method Summary
        content...
    """

    heading_prefix = "#" * heading_level
    markdown = f"{heading_prefix} {self.title}"

    if self.content:
      markdown += f"{self.content}"

    if self.evidence_ids:
      evidence_text = ", ".join(self.evidence_ids)
      markdown += f"\n**Evidence:** {evidence_text}"

    return markdown.strip()
  

class FinalReport(BaseModel):
  """
    Final paper reading report generated by Writer Agent.
    
    This object is still a data model. Actually file writing should be handled by a seperate exporter or by CLI layer.
  """

  title:str = Field(default="Paper Reading Report")
  paper_title:str|None = Field(default=None)
  sections:list[ReportSection] = Field(default_factory=list)

  format:ReportFormat = Field(default=ReportFormat.MARKDOWN)
  output_path:str|None = Field(default=None)

  markdown_content:str|None = Field(
    default=None,
    description="Cached full markdown context. It can be generated from sections."
  )

  metadata:dict[str, Any] = Field(default_factory=dict)

  @field_validator("title", "paper_title", "output_path", "markdown_content")
  @classmethod
  def strip_optional_text(cls, value:str|None) -> str|None:
    if value is None:
      return None
    value = value.strip()
    return value or None
  
  def sorted_sections(self) -> list[ReportSection]:
    """Return secions sorted by their order field"""
    return sorted(self.sections, key=lambda section: section.order)
  
  def to_markdown(self) -> str:
    """
      convert the whole report to Markdown.

      if markdown_content is already provided, return it directly.
      Otherwise, generate markdown from sections.
    """

    if self.markdown_content:
      return self.markdown_content.strip()
    
    lines:list[str] = [f"# {self.title}"]

    if self.paper_title:
      lines.append("")
      lines.append(f"**Paper:** {self.paper_title}")

    for section in self.sorted_sections():
      lines.append("")
      lines.append(section.to_markdown(heading_level=2))

    return "\n".join(lines).strip()

  def section_titles(self) -> list[str]:
    """return report section titles."""
    return [section.title for section in self.sorted_sections()]
  
  def add_section(self, section:ReportSection) -> None:
    """Append one section to the report."""
    self.sections.append(section)